export const en_US = {
    filterAction: 'filter',
    needAction: 'I need',
    directionsAction: 'Directions',
    phoneCallAction: 'Call',
    smsAction: 'Text',
    saveAction: 'Save',
    filterSelectionTitle: 'Show people who need',
    doneAction: 'Done',
    phoneNumberLabel: 'Phone Number',
    nameLabel: 'Name',
    addressLabel: 'Address',
    deleteMarkerAction: 'No Longer Needed',
    cancelAction: 'Cancel',
    myNeedsListTitle: 'My Needs',
    createNeedAction: 'Create New Need',
    locationPermissionRequestTitle: 'Location for needs',
    locationPermissionRequestMessage: 'App needs access to your location so you can find others in need or request your needs.',
    contact: 'Contact',
    eula: 'EULA',
    updateAction: 'Update',
    myInfo: 'My Info',
    aboutDev: 'Supported by Houston\'s creative community \n and the team at ChaiOne',
    anything: 'Anything'
}