export const es = {
    filterAction: 'filter',
    needAction: 'I need',
    directionsAction: 'Directions',
    phoneCallAction: 'Call',
    smsAction: 'Text',
    saveAction: 'Save',
    filterSelectionTitle: 'Show people who need',
    doneAction: 'Done',
    phoneNumberLabel: 'Phone Number',
    nameLabel: 'Name',
    addressLabel: 'Address',
    deleteMarkerAction: 'No Longer Needed',
    cancelAction: 'Cancel',
    myNeedsListTitle: 'My Needs',
    createNeedAction: 'Create New Need',
    locationPermissionRequestTitle: 'Location for needs',
    locationPermissionRequestMessage: 'App needs access to your location so you can find others in need or request your needs.',
}