export const es = {
    filterAction: 'filtro',
    needAction: 'Necesito',
    directionsAction: 'Direcciones',
    phoneCallAction: 'Llamar',
    smsAction: 'Textear',
    saveAction: 'Guardar',
    filterSelectionTitle: 'Mostrar personas que necesitan',
    doneAction: 'Terminar',
    phoneNumberLabel: 'Numero telefonico',
    nameLabel: 'Nombre',
    addressLabel: 'Direccion',
    deleteMarkerAction: 'Ya no necesario',
    cancelAction: 'Cancelar',
    myNeedsListTitle: 'Mis necesidades',
    createNeedAction: 'Crear nueva necesidad',
    locationPermissionRequestTitle: 'Localizacion para necesidades',
    locationPermissionRequestMessage: 'La aplicacion necesita acceso a su localizacion para que pueda encontrar encontrar a otros o ingresar sus propias necesidades.',
    contact: 'Contacto',
    eula: 'Terminos',
    updateAction: 'Actualizar',
    myInfo: 'Mi información',
    aboutDev: 'Supported by Houston\'s creative community \n and the team at ChaiOne',
    anything: 'Anything'
}
