export const hi = {
    filterAction: 'फिल्टर',
    needAction: 'मुझे चाहिए',
    directionsAction: 'नक्शा',
    phoneCallAction: 'कॉल',
    smsAction: 'टेक्स्ट',
    saveAction: 'सेव',
    filterSelectionTitle: 'जरूरतमंद लोगों को दिखाएं',
    doneAction: 'पूर्ण',
    phoneNumberLabel: 'फ़ोन नंबर',
    nameLabel: 'नाम',
    addressLabel: 'पता',
    deleteMarkerAction: 'अब जरूरत नहीं',
    cancelAction: 'रद्द करें',
    myNeedsListTitle: 'मेरी जरूरते',
    createNeedAction: 'नई जरूरत',
    locationPermissionRequestTitle: 'स्थान सेवाओं की अनुमति',
    locationPermissionRequestMessage: 'ऐप को आपके स्थान तक पहुंचने की आवश्यकता है ताकि आप दूसरों को अपनी ज़रूरतों का पता लगा सकें या उनकी ज़रूरतों का अनुरोध कर सकें',
    contact: 'संपर्क करें',
    eula: 'EULA',
    updateAction: 'अपडेट करें',
    myInfo: 'मेरी जानकारी',
    aboutDev: 'हॉस्टन के रचनात्मक समुदाय और चाय टीम द्वारा समर्थित',
    anything: 'हर चीज'
  }
